
map ctrl+shift+f5 load_config_file

# open new tab in same dir
map f1 new_tab_with_cwd

# prompt to detach current tab
# prompt to detach current window
map f2 detach_window ask

# save session with F7+S
map f7>s save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions

# load session with F7+C
map f7>c goto_session ~/.local/share/kitty/sessions/dev.kitty-session
