
# Hyprland colors from hellwal
source = ~/.cache/hellwal/hyprland-colors.conf

general {
    # Gradient with hellwal accents.
    col.active_border = $color4 $color5 $color6 $color7
    col.inactive_border = $color0
}
